# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TJHX4OIRaBeuR1tyDck3tmfJ0FcenT5_
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""# Load the Dataset"""

df=pd.read_csv('/Sleep_health_and_lifestyle_dataset.csv')

"""# Data Understanding"""

df.head()

df.head()

df.dtypes

df.info()

df.shape

df.describe()

"""# Check Missing Values"""

df.isnull().sum()

"""# **Sleep disorder has missing values so remove them**"""

df=df.dropna()

"""# so we droped the all null values in sleep discorder colum"""

df.isnull().sum()

df.info()

"""# Check Duplicate Rows"""

df.duplicated().sum()

"""it shows zero so no dupicated rows"""

df=df.drop_duplicates()

"""hey we have seen blood pressumes coloum has 2 values so we are slpiting it

## **spliting coloums**
"""

df.head()

df[['Systolic', 'Diastolic']] = df['Blood Pressure'].str.split('/', expand=True)

df

"""we have slipt blood pressure into 2 colums

## Check Unique Values
"""

df['Gender'].unique()

df['Occupation'].unique()

df['Sleep Disorder'].unique()

"""# Check Value **Counts**"""

df['Sleep Disorder'].value_counts()

df['BMI Category'].value_counts()

"""load the cleanded data"""

df.to_csv("clean_sleep_dataset.csv", index=False)

"""## NOW WE WILL DO Exploratory Data **Analysis**"""

df = pd.read_csv("/content/clean_sleep_dataset.csv")
df.head()

"""## Understand Distribution of **Age**"""

plt.figure(figsize=(8,5))
sns.histplot(df['Age'],bins=20)
plt.title('Age Distribution')
plt.xlabel('Age')
plt.ylabel('Count')

"""observations:The age distribution shows that most individuals fall between 42 and 46 years old. The dataset ranges from approximately 28 to 59 years, with a slight right skew indicating the presence of older individuals beyond the main age group."""

sns.countplot(x='Gender',data=df)
plt.title('Gender disturabution')

"""insghts: more females are in the data set ,which mean means have higher stress then compare to men

**Sleep Duration Distribution**
"""

plt.figure(figsize=(8,5))
sns.histplot(df['Sleep Duration'],bins=20)
plt.title('Sleep Duration Distribution')
plt.xlabel('Sleep Duration')
plt.ylabel('frequency')

df['Sleep Duration'].mean()

df['Sleep Duration'].max()

df['Sleep Duration'].min()

"""**insight:**L:The sleep duration distribution shows that most individuals sleep between 6 and 6.8 hours, with an average sleep duration of approximately 6.5 hours. The majority of participants sleep less than the recommended 7 hours per night, while a smaller group sleeps around 8 hours.

# *Stress Level vs Sleep Duration*
"""

plt.figure(figsize=(8,5))
sns.scatterplot(x='Stress Level',y='Sleep Duration',data=df)
plt.title('Stress Level vs Sleep Duration')
plt.xlabel('Stress Level')
plt.ylabel('Sleep Duration')

"""insight:Higher stress levels tend to be associated with shorter sleep duration.

# **Sleep Quality by Gender**
"""

sns.boxplot(x='Gender', y='Quality of Sleep', data=df)

plt.title("Sleep Quality by Gender")

plt.show()

"""insights:Female participants generally report higher sleep quality, with a median around 7, compared to males whose median sleep quality is around 6. Female sleep quality also shows a wider variation."
"""

plt.figure(figsize=(8,5))

sns.scatterplot(x='Physical Activity Level', y='Quality of Sleep', data=df)

plt.title("Physical Activity vs Sleep Quality")

plt.show()

""""Higher levels of physical activity appear to be associated with better sleep quality. Individuals with activity levels above 70 generally report sleep quality scores between 7 and 9.

# **Correlation Heatmap**
"""

corr = df.corr(numeric_only=True)

plt.figure(figsize=(10,6))

sns.heatmap(corr, annot=True)

plt.title("Correlation Matrix")

plt.show()

"""Sleep duration strongly improves sleep quality.

Stress significantly reduces both sleep quality and sleep duration.

Physical activity is strongly linked with daily steps and better health indicators.

***Daily Steps vs Sleep Duration***
"""

sns.scatterplot(x='Daily Steps', y='Sleep Duration', data=df)

plt.title("Daily Steps vs Sleep Duration")

plt.show()

"""# **Does Age Affect Sleep Patterns?**"""

plt.figure(figsize=(8,5))

sns.scatterplot(x='Age', y='Sleep Duration', data=df)

plt.title("Age vs Sleep Duration")
plt.xlabel("Age")
plt.ylabel("Sleep Duration")

plt.show()

"""**Does Stress Level Affect Sleep Duration?**"""

plt.figure(figsize=(8,5))

sns.scatterplot(x='Stress Level', y='Sleep Duration', data=df)

plt.title("Stress Level vs Sleep Duration")

plt.show()

"""# **Does Physical Activity Improve Sleep Quality?**"""

plt.figure(figsize=(8,5))

sns.scatterplot(x='Physical Activity Level', y='Quality of Sleep', data=df)

plt.title("Physical Activity vs Sleep Quality")

plt.show()

"""**Which Occupations Have Poor Sleep Quality?**"""

plt.figure(figsize=(10,6))

sns.boxplot(x='Occupation', y='Quality of Sleep', data=df)

plt.xticks(rotation=45)

plt.title("Sleep Quality by Occupation")

plt.show()

"""# **Are Sleep Disorders Related to Lifestyle Habits?**"""

plt.figure(figsize=(8,5))

sns.boxplot(x='Sleep Disorder', y='Stress Level', data=df)

plt.title("Stress Level by Sleep Disorder")

plt.show()

"""# **Correlation Heatmap**"""

plt.figure(figsize=(10,6))

corr = df.corr(numeric_only=True)

sns.heatmap(corr, annot=True)

plt.title("Correlation Heatmap")

plt.show()